# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'G-3Y24L55KZZ'
# disqus-ID: x
# utterances-repo: x


assets:
  logo: '/assets/site/3.svg' 
  badge: '/assets/site/4.svg' 

menu:
# - {name: 'Tutorials', file: '/tutorials.html'}
- {name: 'Docs', file: 'https://linktransformer.readthedocs.io/en/latest/'}

social:
# - {name: 'slack', icon: 'fab fa-slack-hash', link: ''}
- {name: 'Github', icon: 'fab fa-github', link: 'https://github.com/dell-research-harvard/linktransformer'}

# tutorials:
#   categories:
#     - {name: 'starter', title: 'Starter Example'}
#     - {name: 'usecase', title: 'Use Cases'}

footnote: >
  Created and maintained by LinkTransformer Developers. Built with [jekyll](https://jekyllrb.com/) and [bulma](http://bulma.io/).
